local localization = {
	-- unsafe
	["UI_UNSAFE_MONEYLOOP_750k"] = "Money loop - 750k",
	["UI_UNSAFE_MONEYLOOP_500k"] = "Money loop - 500k",
	-- history
	["UI_HISTORY_COPY_RID"] = "Copy RID",
	["UI_HISTORY_COPY_NAME"] = "Copy name",
	["UI_HISTORY_JOIN"] = "Join",
	-- Ceo control
	--Warehouse
	["UI_CC_WAREHOUSE"] = "Warehouse",
	["UI_CC_REMOVE_WAR._BUY_COOLDOWN"] = "Remove war. buy cooldown",
	["UI_CC_REMOVE_WAR._SELL_COOLDOWN"] = "Remove war. sell cooldown",
	["UI_CC_MODDED_WAR._PRICES"] = "Modded war. prices",
	--Vehicle cargo
	["UI_CC_VEHICLE_CARGO"] = "Vehicle cargo",
	["UI_CC_REMOVE_VEH-CARGO_COOLDOWNS"] = "Remove veh-cargo cooldowns",
	["UI_CC_MODDED_VEH-CARGO_PRICES"] = "Modded veh-cargo prices",
	--Air Freight
	["UI_CC_AIR_FREIGHT"] = "Air Freight",
	["UI_CC_REMOVE_AIR-FREIGHT_COOLDOWNS"] = "Remove air-freight cooldowns",
	["UI_CC_MODDED_AIR-FREIGHT_PRICES"] = "Modded air-freight prices",
	--Contracts
	["UI_CC_CONTRACTS"] = "Contracts",
	["UI_CC_REMOVE_VIP_COOLDOWN"] = "Remove vip cooldown",
	["UI_CC_REMOVE_CLIENTS_COOLDOWNS"] = "Remove clients cooldowns",
	--Kosatka
	["UI_CC_KOSATKA"] = "Kosatka",
	["UI_CC_REMOVE_MISSILES_COOLDOWN"] = "Remove missiles cooldown",
	["UI_CC_INFINITE_MISSILES"] = "Infinite missiles",
	--MotoClub
	["UI_CC_MC"] = "MC",
	["UI_CC_MODDED_MC_RESUPPLY_COST"] = "Modded mc resupply cost",
	["UI_CC_MODDED_MC_SIGNAL_TIME"] = "Modded mc signal time",
	["UI_CC_MODDED_MC_STOCK"] = "Modded mc stock",
	["UI_CC_MODDED_MC_UNITS"] = "Modded mc units",
	["UI_CC_MODDED_MC_UNITS_PRICE"] = "Modded mc units price",
	["UI_CC_MODDED_MC_PRODUCTION"] = "Modded mc production",
	["UI_CC_MODDED_MC_SELL_MULTS"] = "Modded mc sell mults",
	["UI_CC_MODDED_MC_BUY_PRICE"] = "Modded mc buy price",
	--Bunker
	["UI_CC_BUNKER"] = "Bunker",
	["UI_CC_REMOVE_BUNKER_RESUPPLY_COST"] = "Remove bunker resupply cost",
	["UI_CC_MODDED_BUNKER_SELL_MULTS"] = "Modded bunker sell mults",
	["UI_CC_MODDED_BUNKER_UNITS_PRICE"] = "Modded bunker units price",
	["UI_CC_MODDED_BUNKER_PRODUCTION"] = "Modded bunker production",
	--Nightclub
	["UI_CC_NIGHTCLUB"] = "Nightclub",
	["UI_CC_REMOVE_NC_PROMOTE_COOLDOWN"] = "Remove nc promote cooldown",
	["UI_CC_REMOVE_NC_SELL_COOLDOWN"] = "Remove nc sell cooldown",
	["UI_CC_MODDED_NC_SELL_PRICES"] = "Modded nc sell prices",
	--Tuners
	["UI_CC_TUNERS"] = "Tuners",
	["UI_CC_REMOVE_TUNER_REPAIR_PRICE"] = "Remove tuner repair price",
	["UI_CC_MODDED_TUNER_SELL_PRICE"] = "Modded tuner sell price",
	--Arcade (Ceo Final)
	["UI_CC_ARCADE"] = "Arcade",
	["UI_CC_MODDED_ARCADE_INCOME"] = "Modded arcade income",
	-- Player manager
	["UI_PM_OPTIONS"] = "Options",
	["UI_PM_UPDATE_PLAYERS"] = "Update players",
	["UI_PM_FOLDERS"] = "Folders",
	["UI_PM_FOLDER"] = "Folder: ",
	["UI_PM_ADD_PLAYER"] = "Add player",
	["UI_PM_NAME"] = "Name:",
	["UI_PM_RID"] = "RID:",
	["UI_PM_NOTE"] = "Note:",
	["UI_PM_JOIN"] = "Join",
	["UI_PM_IP"] = "Last IP:",
	["UI_PM_SEEN_FIRST"] = "First seen:",
	["UI_PM_SEEN_LAST"] = "Last seen:",
	["UI_PM_MODDER"] = "Modder",
	["UI_PM_UPDATE_ONLINE"] = "Update online",
	["UI_PM_UPDATE_NOTIFY"] = "Notify",
	--Join reactions
	["UI_PM_JOIN_REACTIONS"] = "Join reactions",
	["UI_PM_REACTION_BLOCK_CHAT"] = "Block chat",
	["UI_PM_REACTION_BLOCK_JOINS"] = "Block joins",
	["UI_PM_REACTION_BLOCK_SCRIPTS"] = "Block scripts",
	["UI_PM_REACTION_BLOCK_SYNC"] = "Block sync",
	["UI_PM_REACTION_CRASH"] = "Crash",
	["UI_PM_REACTION_EXPLODE"] = "Explode",
	["UI_PM_REACTION_FREEZE"] = "Freeze",
	["UI_PM_REACTION_KICK"] = "Kick",
	-- Garage
	["UI_GARAGE_UPDATE"] = "Update vehicles",
	["UI_GARAGE_DEFAULT"] = "Default garage",
	-- Heist control
	["UI_HC_INFINITE_LIVES_IN_MISSIONS"] = "Infinite lives in missions",
	["UI_HC_PRESETS"] = "Presets",
	["UI_HC_CAYO"] = "Cayo",
	["UI_HC_FEE"] = "Fee",
	["UI_HC_REMOVE_PAVEL_FEE"] = "Remove Pavel fee",
	["UI_HC_REMOVE_ESCAPE_FEE"] = "Remove escape fee",
	["UI_HC_AUTOFINISH_PRIMARY_TARGET"] = "Autofinish primary target",
	["UI_HC_INSTANT_FINGERPRINT_CRACK"] = "Instant fingerprint crack",
	["UI_HC_INFINITE_VOLTAGE_TIMER"] = "Infinite voltage timer",
	["UI_HC_REMOVE_DRAINAGE_PIPE"] = "Remove Drainage Pipe",
	["UI_HC_CASINO"] = "Casino",
	["UI_HC_MODDED_POTENTIAL"] = "Modded potential",
	["UI_HC_INSTANT_VAULT_DOOR_LASER"] = "Instant vault door laser",
	["UI_HC_INSTANT_CASINO_DOOR_CRACK"] = "Instant door crack",
	["UI_HC_DOOMSDAY"] = "Doomsday",
	["UI_HC_CLASSIC_HEISTS"] = "Classic heists",
	["UI_HC_TUNERS"] = "Tuners",
	["UI_HC_1M_PAYOUT"] = "1M payout",
	["UI_HC_REMOVE_IA_FEE"] = "Remove IA fee",
	["UI_HC_CONTRACT"] = "Contract",
	["UI_HC_REMOVE_COOLDOWNS"] = "Remove cooldowns",
	["UI_HC_DELETE_CAMERAS"] = "Delete cameras",
	["UI_HC_PRESETS_CAYO_QUICK_2.5M"] = "Quick 2.5M",
	["UI_HC_PRESETS_CASINO_DIAMONDS_SILENT"] = "Diamonds - Silent",
	["UI_HC_PRESETS_CASINO_DIAMONDS_SILENT_2.45M"] = "Diamonds - Silent | 2.45M",
	["UI_HC_PRESETS_CASINO_DIAMONDS_BIGCON"] = "Diamonds - BigCon",
	["UI_HC_PRESETS_CASINO_DIAMONDS_BIGCON_2.45M"] = "Diamonds - BigCon | 2.45M",
	["UI_HC_PRESETS_CASINO_DIAMONDS_AGGRESSIVE"] = "Diamonds - Aggressive",
	["UI_HC_PRESETS_CASINO_DIAMONDS_AGGRESSIVE_2.45M"] = "Diamonds - Aggressive | 2.45M",
	--ACT1
	["UI_HC_PRESET_DOOMSDAY_ACT1"] = "ACT I : The Data Breaches",
	["UI_HC_PRESET_DOOMSDAY_ACT1_2.5M"] = "ACT I : The Data Breaches | 2.5M",
	--ACT2
	["UI_HC_PRESET_DOOMSDAY_ACT2"] = "ACT II : The Bogdan Problem",
	["UI_HC_PRESET_DOOMSDAY_ACT2_2.5M"] = "ACT II : The Bogdan Problem | 2.5M",
	--ACT3
	["UI_HC_PRESET_DOOMSDAY_ACT3"] = "ACT III : The Doomsday Scenario",
	["UI_HC_PRESET_DOOMSDAY_ACT3_2.5M"] = "ACT III : The Doomsday Scenario | 2.5M",
	["UI_HC_PRESETS_FLEECA_15M"] = "Fleeca 15M",
	["UI_HC_PRESETS_CONTRACT_FINAL_2.4M"] = "Final 2.4M",
	["UI_HC_PRESETS_UNION_DEPOSITORY"] = "Union Depository",
	["UI_HC_PRESETS_THE_SUPERDOLLAR_DEAL"] = "The Superdollar Deal",
	["UI_HC_PRESETS_THE_BANK_CONTRACT"] = "The Bank Contract",
	["UI_HC_PRESETS_THE_ECU"] = "The ECU Job",
	["UI_HC_PRESETS_THE_PRISON_CONTRACT"] = "The Prison Contract",
	["UI_HC_PRESETS_THE_AGENCY_DEAL"] = "The Agency Deal",
	["UI_HC_PRESETS_THE_LOST_CONTRACT"] = "The Lost Contract",
	["UI_HC_PRESETS_THE_DATA_CONTRACT"] = "The Data Contract",
	["UI_HC_PRESETS_RESET_GC"] = "Reset Gains & Completes",
	["UI_HC_PRESETS_COMPLETE_MISSIONS"] = "Complete missions",
	["UI_HC_PRESETS_PREP_THE_NIGHTCLUB"] = "The Nightclub (Prep)",
	["UI_HC_PRESETS_PREP_THE_MARINA"] = "The Marina (Prep)",
	["UI_HC_PRESETS_MISSION_NIGHTLIFE_LEAK"] = "NightLife Leak (Mission)",
	["UI_HC_PRESETS_PREP_THE_COUNTRY_CLUB"] = "The Country Club (Prep)",
	["UI_HC_PRESETS_PREP_GUEST_LIST"] = "Guest List (Prep)",
	["UI_HC_PRESETS_MISSION_HIGH_SOCIETY"] = "High Society (Mission)",
	["UI_HC_PRESETS_PREP_DAVIS"] = "Davis (Prep)",
	["UI_HC_PRESETS_PREP_THE_BALLAS"] = "The Ballas (Prep)",
	["UI_HC_PRESETS_MISSION_AGENCY_STUDIO"] = "Agency Studio (Mission)",
	["UI_HC_PRESETS_FINAL_CONTRACT"] = "Final Contract: Don't Fuck with Dre",
	-- Outfits
	["UI_OUTFITS_UPDATE"] = "Update",
	["UI_OUTFITS_SAVE"] = "Save current",
}

return localization