local stats = {
	cayo = {
		only_primary = {{"H4CNF_BS_GEN", 262143},{"H4CNF_BS_ENTR", 63},{"H4CNF_BS_ABIL", 63},{"H4CNF_WEP_DISRP", 3},{"H4CNF_ARM_DISRP", 3},{"H4CNF_HEL_DISRP", 3},{"H4CNF_BOLTCUT", 4424},{"H4CNF_UNIFORM", 5256},{"H4CNF_GRAPPEL", 5156},{"H4CNF_APPROACH", 0xFFFFFFF},{"H4LOOT_CASH_I", 0},{"H4LOOT_CASH_C", 0},{"H4LOOT_WEED_I", 0},{"H4LOOT_WEED_C", 0},{"H4LOOT_COKE_I", 0},{"H4LOOT_COKE_C", 0},{"H4LOOT_GOLD_I", 0},{"H4LOOT_GOLD_C", 0},{"H4LOOT_PAINT", 0},{"H4LOOT_CASH_V", 0},{"H4LOOT_COKE_V", 0},{"H4LOOT_GOLD_V", 0},{"H4LOOT_PAINT_V", 0},{"H4LOOT_WEED_V", 0},{"H4LOOT_CASH_I_SCOPED", 0},{"H4LOOT_CASH_C_SCOPED", 0},{"H4LOOT_WEED_I_SCOPED", 0},{"H4LOOT_WEED_C_SCOPED", 0},{"H4LOOT_COKE_I_SCOPED", 0},{"H4LOOT_COKE_C_SCOPED", 0},{"H4LOOT_GOLD_I_SCOPED", 0},{"H4LOOT_GOLD_C_SCOPED", 0},{"H4LOOT_PAINT_SCOPED", 0},{"H4CNF_TARGET", 5},{"H4CNF_WEAPONS", 1},{"H4_MISSIONS", 65283},{"H4_PROGRESS", 126823},{"H4_PLAYTHROUGH_STATUS", 5}}
	},
	casino = {
		diamonds = {
			silent = {{"H3OPT_MODVEH", -1}, {"H3_COMPLETEDPOSIX", -1}, {"CAS_HEIST_FLOW", -1}, {"H3_LAST_APPROACH", 0}, {"H3OPT_APPROACH", 1}, {"H3_HARD_APPROACH", 0}, {"H3OPT_TARGET", 3}, {"H3OPT_POI", 1023}, {"H3OPT_ACCESSPOINTS", 2047}, {"H3OPT_CREWWEAP", 4}, {"H3OPT_CREWDRIVER", 3}, {"H3OPT_CREWHACKER", 4}, {"H3OPT_WEAPS", 1}, {"H3OPT_VEHS", 3}, {"H3OPT_DISRUPTSHIP", 3}, {"H3OPT_BODYARMORLVL", -1}, {"H3OPT_KEYLEVELS", 2}, {"H3OPT_MASKS", 2}, {"H3OPT_BITSET1", 127}, {"H3OPT_BITSET0", 262270}},
			bigcon = {{"H3OPT_MODVEH", -1}, {"H3_COMPLETEDPOSIX", -1}, {"CAS_HEIST_FLOW", -1}, {"H3_LAST_APPROACH", 0}, {"H3OPT_APPROACH", 2}, {"H3_HARD_APPROACH", 0}, {"H3OPT_TARGET", 3}, {"H3OPT_POI", 1023}, {"H3OPT_ACCESSPOINTS", 2047}, {"H3OPT_CREWWEAP", 4}, {"H3OPT_CREWDRIVER", 3}, {"H3OPT_CREWHACKER", 4}, {"H3OPT_WEAPS", 0}, {"H3OPT_VEHS", 3}, {"H3OPT_DISRUPTSHIP", 3}, {"H3OPT_BODYARMORLVL", -1}, {"H3OPT_KEYLEVELS", 2}, {"H3OPT_MASKS", 2}, {"H3OPT_BITSET1", 159}, {"H3OPT_BITSET0", 524118}},
			aggressive = {{"H3OPT_MODVEH", -1}, {"H3_COMPLETEDPOSIX", -1}, {"CAS_HEIST_FLOW", -1}, {"H3_LAST_APPROACH", 0}, {"H3OPT_APPROACH", 3}, {"H3_HARD_APPROACH", 0}, {"H3OPT_TARGET", 3}, {"H3OPT_POI", 1023}, {"H3OPT_ACCESSPOINTS", 2047}, {"H3OPT_CREWWEAP", 4}, {"H3OPT_CREWDRIVER", 3}, {"H3OPT_CREWHACKER", 4}, {"H3OPT_WEAPS", 1}, {"H3OPT_VEHS", 3}, {"H3OPT_DISRUPTSHIP", 3}, {"H3OPT_BODYARMORLVL", -1}, {"H3OPT_KEYLEVELS", 2}, {"H3OPT_MASKS", 2}, {"H3OPT_BITSET1", 799}, {"H3OPT_BITSET0", 3670102}}
		}
	},
	tuner = {
		union = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 0}},
		superdollar = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 1}},
		bank_contract = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 2}},
		ecu = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 3}},
		prison = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 4}},
		agency = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 5}},
		lost = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 6}},
		data = {{"TUNER_GEN_BS", 12543}, {"TUNER_CURRENT", 7}},

		complete = {{"TUNER_GEN_BS", 0xFFFFFFF}},
		reset_gains = {{"TUNER_COUNT", 0}, {"TUNER_EARNINGS", 0}},
	},
	contract = {
		final = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 4092}, {"FIXER_STORY_COOLDOWN", -1}},

		nightclub = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 3}, {"FIXER_STORY_COOLDOWN", -1}},
		marina = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 4}, {"FIXER_STORY_COOLDOWN", -1}},
		nightlife = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 12}, {"FIXER_STORY_COOLDOWN", -1}},
		country_club = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 28}, {"FIXER_STORY_COOLDOWN", -1}},
		guest_list = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 60}, {"FIXER_STORY_COOLDOWN", -1}},
		high_society = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 124}, {"FIXER_STORY_COOLDOWN", -1}},
		davis = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 252}, {"FIXER_STORY_COOLDOWN", -1}},
		ballas = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 508}, {"FIXER_STORY_COOLDOWN", -1}},
		agency_studio = {{"FIXER_GENERAL_BS", -1}, {"FIXER_COMPLETED_BS", -1}, {"FIXER_STORY_BS", 2044}, {"FIXER_STORY_COOLDOWN", -1}},
	},
	doomsday = {
		act1 = {{"GANGOPS_FLOW_MISSION_PROG", 503}, {"GANGOPS_HEIST_STATUS", -229383}, {"GANGOPS_FLOW_NOTIFICATIONS", 1557}},
		act2 = {{"GANGOPS_FLOW_MISSION_PROG", 240}, {"GANGOPS_HEIST_STATUS", -229378}, {"GANGOPS_FLOW_NOTIFICATIONS", 1557}},
		act3 = {{"GANGOPS_FLOW_MISSION_PROG", 16368}, {"GANGOPS_HEIST_STATUS", -229380}, {"GANGOPS_FLOW_NOTIFICATIONS", 1557}},
	},
	classic = {}
}

return stats