local POSITIONS = {
    -- PERICO
    ["P_BOARD"] = Vector3(1561.224, 386.659, -49.685),
    ["P_DECK"] = Vector3(1563.218, 406.030, -49.667),
    ["P_FIRST_TUNNEL"] = Vector3(5044.726, -5816.164, -11.213),
    ["P_SECOND_TUNNEL"] = Vector3(5054.630, -5771.519, -4.807),
    ["P_MAIN_TARGET"] = Vector3(5006.896, -5755.963, 15.487),
    ["P_SECONDARY_TARGET"] = Vector3(5003.467, -5749.352, 14.840),
    ["P_VAULT"] = Vector3(5010.753, -5757.639, 28.845),
    ["P_REDUCT"] = Vector3(4992.854, -5718.537, 19.880),
    ["P_OCEAN"] = Vector3(4771.792, -6166.055, -40.266),
    -- Casino
    ["C_BOARD"] = Vector3(2711.773, -369.458, -54.781),
    ["C_GARAGE"] = Vector3(2677.237, -361.494, -55.187),
    -- Doomsday
    ["D_SCREEN"] = Vector3(515.528, 4835.353, -62.587),
    ["D_CELL"] = Vector3(512.888, 4833.033, -68.989),
}

local function SET_INT_GLOBAL(global, value)
    script_global:new(global):set_int64(value)
end
local function SET_FLOAT_GLOBAL(global, value)
    script_global:new(global):set_float(value)
end

local formats = {
    "MP0_%s",
    "MP1_%s"
}

local function STAT_SET_INT(hash, value)
    for _, f in ipairs(formats) do
        STATS.STAT_SET_INT(string.smart_joaat(f:format(hash)), value, true)
    end
end
local function STAT_SET_FLOAT(hash, value)
    for _, f in ipairs(formats) do
        STATS.STAT_SET_FLOAT(string.smart_joaat(f:format(hash)), value, true)
    end
end
local function STAT_SET_BOOL(hash, value)
    for _, f in ipairs(formats) do
        STATS.STAT_SET_BOOL(string.smart_joaat(f:format(hash)), value, true)
    end
end

local PRESETS = {
    ["P_QUICK"] = function()
        STAT_SET_INT("H4CNF_BS_GEN", 262143)
        STAT_SET_INT("H4CNF_BS_ENTR", 63)
        STAT_SET_INT("H4CNF_BS_ABIL", 63)
        STAT_SET_INT("H4CNF_WEP_DISRP", 3)
        STAT_SET_INT("H4CNF_ARM_DISRP", 3)
        STAT_SET_INT("H4CNF_HEL_DISRP", 3)
        STAT_SET_INT("H4CNF_BOLTCUT", 4424)
        STAT_SET_INT("H4CNF_UNIFORM", 5256)
        STAT_SET_INT("H4CNF_GRAPPEL", 5156)
        STAT_SET_INT("H4CNF_APPROACH", 0xFFFFFFF)
        STAT_SET_INT("H4LOOT_CASH_I", 0)
        STAT_SET_INT("H4LOOT_CASH_C", 0)
        STAT_SET_INT("H4LOOT_WEED_I", 0)
        STAT_SET_INT("H4LOOT_WEED_C", 0)
        STAT_SET_INT("H4LOOT_COKE_I", 0)
        STAT_SET_INT("H4LOOT_COKE_C", 0)
        STAT_SET_INT("H4LOOT_GOLD_I", 0)
        STAT_SET_INT("H4LOOT_GOLD_C", 0)
        STAT_SET_INT("H4LOOT_PAINT", 0)
        STAT_SET_INT("H4LOOT_CASH_V", 0)
        STAT_SET_INT("H4LOOT_COKE_V", 0)
        STAT_SET_INT("H4LOOT_GOLD_V", 0)
        STAT_SET_INT("H4LOOT_PAINT_V", 0)
        STAT_SET_INT("H4LOOT_WEED_V", 0)
        STAT_SET_INT("H4LOOT_CASH_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_CASH_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_WEED_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_WEED_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_COKE_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_COKE_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_PAINT_SCOPED", 0)
        STAT_SET_INT("H4CNF_TARGET", 5)
        STAT_SET_INT("H4CNF_WEAPONS", 1)
        STAT_SET_INT("H4_MISSIONS", 65283)
        STAT_SET_INT("H4_PROGRESS", 126823)
        STAT_SET_INT("H4_PLAYTHROUGH_STATUS", 5)
        -- INT
        SET_INT_GLOBAL(1711169,100)
        SET_INT_GLOBAL(1711170,145)
        SET_INT_GLOBAL(1711171,145)
        SET_INT_GLOBAL(1711172,145)
        SET_FLOAT_GLOBAL(262145+29470,0.0)
        SET_FLOAT_GLOBAL(262145+29471,0.0)
        SET_INT_GLOBAL(262145 + 29466,2455000)
    end,
    ["P_SOLO"] = function()
        STAT_SET_INT("H4CNF_BOLTCUT", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_UNIFORM", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_GRAPPEL", 0xFFFFFFF)
        STAT_SET_INT("H4_MISSIONS", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_WEAPONS", 1)
        STAT_SET_INT("H4CNF_TROJAN", 5)
        STAT_SET_INT("H4_PLAYTHROUGH_STATUS", 100)
        STAT_SET_INT("H4CNF_TARGET", 5)
        STAT_SET_INT("H4LOOT_CASH_I", 5551206)
        STAT_SET_INT("H4LOOT_CASH_I_SCOPED", 5551206)
        STAT_SET_INT("H4LOOT_CASH_C", 0)
        STAT_SET_INT("H4LOOT_CASH_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_COKE_I", 4884838)
        STAT_SET_INT("H4LOOT_COKE_I_SCOPED", 4884838)
        STAT_SET_INT("H4LOOT_COKE_C", 0)
        STAT_SET_INT("H4LOOT_COKE_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_I", 0)
        STAT_SET_INT("H4LOOT_GOLD_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_C", 192)
        STAT_SET_INT("H4LOOT_GOLD_C_SCOPED", 192)
        STAT_SET_INT("H4LOOT_WEED_I", 0)
        STAT_SET_INT("H4LOOT_WEED_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_WEED_C", 0)
        STAT_SET_INT("H4LOOT_WEED_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_PAINT", 120)
        STAT_SET_INT("H4LOOT_PAINT_SCOPED", 120)
        STAT_SET_INT("H4LOOT_CASH_V", 224431)
        STAT_SET_INT("H4LOOT_COKE_V", 353863)
        STAT_SET_INT("H4LOOT_GOLD_V", 471817)
        STAT_SET_INT("H4LOOT_PAINT_V", 353863)
        STAT_SET_INT("H4LOOT_WEED_V", 0)
        STAT_SET_INT("H4_PROGRESS", 131055)
        STAT_SET_INT("H4CNF_BS_GEN", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_BS_ENTR", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_BS_ABIL", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_WEP_DISRP", 3)
        STAT_SET_INT("H4CNF_ARM_DISRP", 3)
        STAT_SET_INT("H4CNF_HEL_DISRP", 3)
        STAT_SET_INT("H4CNF_APPROACH", 0xFFFFFFF)
        -- INT
        SET_FLOAT_GLOBAL(262145+29470,-0.1)
        SET_FLOAT_GLOBAL(262145+29471,-0.02)
        SET_INT_GLOBAL(262145+29227,1800)
        SET_INT_GLOBAL(1711169,100)
    end,
    ["P_SOLO2"] = function()
        STAT_SET_INT("H4CNF_TARGET", 1)
        STAT_SET_INT("H4LOOT_CASH_I", 9208137)
        STAT_SET_INT("H4LOOT_CASH_I_SCOPED", 9208137)
        STAT_SET_INT("H4LOOT_CASH_C", 0)
        STAT_SET_INT("H4LOOT_CASH_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_COKE_I", 1048704)
        STAT_SET_INT("H4LOOT_COKE_I_SCOPED", 1048704)
        STAT_SET_INT("H4LOOT_COKE_C", 0)
        STAT_SET_INT("H4LOOT_COKE_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_I", 0)
        STAT_SET_INT("H4LOOT_GOLD_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_C", 255)
        STAT_SET_INT("H4LOOT_GOLD_C_SCOPED", 255)
        STAT_SET_INT("H4LOOT_WEED_I", 4206596)
        STAT_SET_INT("H4LOOT_WEED_I_SCOPED", 4206596)
        STAT_SET_INT("H4LOOT_WEED_C", 0)
        STAT_SET_INT("H4LOOT_WEED_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_PAINT", 127)
        STAT_SET_INT("H4LOOT_PAINT_SCOPED", 127)
        STAT_SET_INT("H4LOOT_CASH_V", 424431)
        STAT_SET_INT("H4LOOT_COKE_V", 848863)
        STAT_SET_INT("H4LOOT_GOLD_V", 1131817)
        STAT_SET_INT("H4LOOT_PAINT_V", 848863)
        STAT_SET_INT("H4LOOT_WEED_V", 679090)
        STAT_SET_INT("H4_PROGRESS", 131055)
        STAT_SET_INT("H4CNF_BS_GEN", 262143)
        STAT_SET_INT("H4CNF_BS_ENTR", 63)
        STAT_SET_INT("H4CNF_BS_ABIL", 63)
        STAT_SET_INT("H4CNF_WEP_DISRP", 3)
        STAT_SET_INT("H4CNF_ARM_DISRP", 3)
        STAT_SET_INT("H4CNF_HEL_DISRP", 3)
        STAT_SET_INT("H4CNF_APPROACH", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_BOLTCUT", 4424)
        STAT_SET_INT("H4CNF_UNIFORM", 5256)
        STAT_SET_INT("H4CNF_GRAPPEL", 5156)
        STAT_SET_INT("H4_MISSIONS", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_WEAPONS", 1)
        STAT_SET_INT("H4CNF_TROJAN", 5)
        STAT_SET_INT("H4_PLAYTHROUGH_STATUS", 100)
        -- INT
        SET_FLOAT_GLOBAL(262145+29470,-0.1)
        SET_FLOAT_GLOBAL(262145+29471,-0.02)
        SET_INT_GLOBAL(262145+29227,1800)
        SET_INT_GLOBAL(1711169,100)
    end,
    ["P_DUAL"] = function()
        STAT_SET_INT("H4CNF_BOLTCUT", 4424)
        STAT_SET_INT("H4CNF_UNIFORM", 5256)
        STAT_SET_INT("H4CNF_GRAPPEL", 5156)
        STAT_SET_INT("H4_MISSIONS", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_WEAPONS", 1)
        STAT_SET_INT("H4CNF_TROJAN", 5)
        STAT_SET_INT("H4_PLAYTHROUGH_STATUS", 100)
        STAT_SET_INT("H4CNF_TARGET", 5)
        STAT_SET_INT("H4LOOT_CASH_I", 2359448)
        STAT_SET_INT("H4LOOT_CASH_I_SCOPED", 2359448)
        STAT_SET_INT("H4LOOT_CASH_C", 0)
        STAT_SET_INT("H4LOOT_CASH_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_COKE_I", 2)
        STAT_SET_INT("H4LOOT_COKE_I_SCOPED", 2)
        STAT_SET_INT("H4LOOT_COKE_C", 0)
        STAT_SET_INT("H4LOOT_COKE_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_I", 0)
        STAT_SET_INT("H4LOOT_GOLD_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_C", 255)
        STAT_SET_INT("H4LOOT_GOLD_C_SCOPED", 255)
        STAT_SET_INT("H4LOOT_WEED_I", 0)
        STAT_SET_INT("H4LOOT_WEED_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_WEED_C", 0)
        STAT_SET_INT("H4LOOT_WEED_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_PAINT", 127)
        STAT_SET_INT("H4LOOT_PAINT_SCOPED", 127)
        STAT_SET_INT("H4LOOT_CASH_V", 474431)
        STAT_SET_INT("H4LOOT_COKE_V", 948863)
        STAT_SET_INT("H4LOOT_GOLD_V", 1265151)
        STAT_SET_INT("H4LOOT_PAINT_V", 948863)
        STAT_SET_INT("H4LOOT_WEED_V", 0)
        STAT_SET_INT("H4_PROGRESS", 126823)
        STAT_SET_INT("H4CNF_BS_GEN", 262143)
        STAT_SET_INT("H4CNF_BS_ENTR", 63)
        STAT_SET_INT("H4CNF_BS_ABIL", 63)
        STAT_SET_INT("H4CNF_WEP_DISRP", 3)
        STAT_SET_INT("H4CNF_ARM_DISRP", 3)
        STAT_SET_INT("H4CNF_HEL_DISRP", 3)
        STAT_SET_INT("H4CNF_APPROACH", 0xFFFFFFF)
        -- INT
        SET_FLOAT_GLOBAL(262145+29470,-0.1)
        SET_FLOAT_GLOBAL(262145+29471,-0.02)
        SET_INT_GLOBAL(262145+29227,1800)
        SET_INT_GLOBAL(1711169,50)
        SET_INT_GLOBAL(1711170,50)
    end,
    ["P_DUAL2"] = function()
        STAT_SET_INT("H4CNF_TARGET", 1)
        STAT_SET_INT("H4LOOT_CASH_I", 9208137)
        STAT_SET_INT("H4LOOT_CASH_I_SCOPED", 9208137)
        STAT_SET_INT("H4LOOT_CASH_C", 0)
        STAT_SET_INT("H4LOOT_CASH_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_COKE_I", 1048704)
        STAT_SET_INT("H4LOOT_COKE_I_SCOPED", 1048704)
        STAT_SET_INT("H4LOOT_COKE_C", 0)
        STAT_SET_INT("H4LOOT_COKE_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_I", 0)
        STAT_SET_INT("H4LOOT_GOLD_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_C", 255)
        STAT_SET_INT("H4LOOT_GOLD_C_SCOPED", 255)
        STAT_SET_INT("H4LOOT_WEED_I", 4206596)
        STAT_SET_INT("H4LOOT_WEED_I_SCOPED", 4206596)
        STAT_SET_INT("H4LOOT_WEED_C", 0)
        STAT_SET_INT("H4LOOT_WEED_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_PAINT", 127)
        STAT_SET_INT("H4LOOT_PAINT_SCOPED", 127)
        STAT_SET_INT("H4LOOT_CASH_V", 572727)
        STAT_SET_INT("H4LOOT_COKE_V", 1145454)
        STAT_SET_INT("H4LOOT_GOLD_V", 1527272)
        STAT_SET_INT("H4LOOT_PAINT_V", 1145454)
        STAT_SET_INT("H4LOOT_WEED_V", 916363)
        STAT_SET_INT("H4_PROGRESS", 126823)
        STAT_SET_INT("H4CNF_BS_GEN", 262143)
        STAT_SET_INT("H4CNF_BS_ENTR", 63)
        STAT_SET_INT("H4CNF_BS_ABIL", 63)
        STAT_SET_INT("H4CNF_WEP_DISRP", 3)
        STAT_SET_INT("H4CNF_ARM_DISRP", 3)
        STAT_SET_INT("H4CNF_HEL_DISRP", 3)
        STAT_SET_INT("H4CNF_APPROACH", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_BOLTCUT", 4424)
        STAT_SET_INT("H4CNF_UNIFORM", 5256)
        STAT_SET_INT("H4CNF_GRAPPEL", 5156)
        STAT_SET_INT("H4_MISSIONS", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_WEAPONS", 1)
        STAT_SET_INT("H4CNF_TROJAN", 5)
        STAT_SET_INT("H4_PLAYTHROUGH_STATUS", 100)
        -- INT
        SET_FLOAT_GLOBAL(262145+29470,-0.1)
        SET_FLOAT_GLOBAL(262145+29471,-0.02)
        SET_INT_GLOBAL(262145+29227,1800)
        SET_INT_GLOBAL(1711169,50)
        SET_INT_GLOBAL(1711170,50)
    end,
    ["P_TRIO"] = function()
        STAT_SET_INT("H4CNF_BOLTCUT", 4424)
        STAT_SET_INT("H4CNF_UNIFORM", 5256)
        STAT_SET_INT("H4CNF_GRAPPEL", 5156)
        STAT_SET_INT("H4_MISSIONS", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_WEAPONS", 1)
        STAT_SET_INT("H4CNF_TROJAN", 5)
        STAT_SET_INT("H4_PLAYTHROUGH_STATUS", 100)
        STAT_SET_INT("H4CNF_TARGET", 5)
        STAT_SET_INT("H4LOOT_CASH_I", 2359448)
        STAT_SET_INT("H4LOOT_CASH_I_SCOPED", 2359448)
        STAT_SET_INT("H4LOOT_CASH_C", 0)
        STAT_SET_INT("H4LOOT_CASH_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_COKE_I", 4901222)
        STAT_SET_INT("H4LOOT_COKE_I_SCOPED", 4901222)
        STAT_SET_INT("H4LOOT_COKE_C", 0)
        STAT_SET_INT("H4LOOT_COKE_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_I", 0)
        STAT_SET_INT("H4LOOT_GOLD_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_C", 255)
        STAT_SET_INT("H4LOOT_GOLD_C_SCOPED", 255)
        STAT_SET_INT("H4LOOT_WEED_I", 0)
        STAT_SET_INT("H4LOOT_WEED_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_WEED_C", 0)
        STAT_SET_INT("H4LOOT_WEED_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_PAINT", 127)
        STAT_SET_INT("H4LOOT_PAINT_SCOPED", 127)
        STAT_SET_INT("H4LOOT_CASH_V", 515151)
        STAT_SET_INT("H4LOOT_COKE_V", 1030303)
        STAT_SET_INT("H4LOOT_GOLD_V", 1373737)
        STAT_SET_INT("H4LOOT_PAINT_V", 1030303)
        STAT_SET_INT("H4LOOT_WEED_V", 0)
        STAT_SET_INT("H4_PROGRESS", 126823)
        STAT_SET_INT("H4CNF_BS_GEN", 262143)
        STAT_SET_INT("H4CNF_BS_ENTR", 63)
        STAT_SET_INT("H4CNF_BS_ABIL", 63)
        STAT_SET_INT("H4CNF_WEP_DISRP", 3)
        STAT_SET_INT("H4CNF_ARM_DISRP", 3)
        STAT_SET_INT("H4CNF_HEL_DISRP", 3)
        STAT_SET_INT("H4CNF_APPROACH", 0xFFFFFFF)
        -- INT
        SET_FLOAT_GLOBAL(262145+29470,-0.1)
        SET_FLOAT_GLOBAL(262145+29471,-0.02)
        SET_INT_GLOBAL(262145+29227,1800)
        SET_INT_GLOBAL(1711169,30)
        SET_INT_GLOBAL(1711170,35)
        SET_INT_GLOBAL(1711171,35)
    end,
    ["P_TRIO2"] = function()
        STAT_SET_INT("H4CNF_TARGET", 1)
        STAT_SET_INT("H4LOOT_CASH_I", 9208137)
        STAT_SET_INT("H4LOOT_CASH_I_SCOPED", 9208137)
        STAT_SET_INT("H4LOOT_CASH_C", 0)
        STAT_SET_INT("H4LOOT_CASH_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_COKE_I", 1048704)
        STAT_SET_INT("H4LOOT_COKE_I_SCOPED", 1048704)
        STAT_SET_INT("H4LOOT_COKE_C", 0)
        STAT_SET_INT("H4LOOT_COKE_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_I", 0)
        STAT_SET_INT("H4LOOT_GOLD_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_C", 255)
        STAT_SET_INT("H4LOOT_GOLD_C_SCOPED", 255)
        STAT_SET_INT("H4LOOT_WEED_I", 4206596)
        STAT_SET_INT("H4LOOT_WEED_I_SCOPED", 4206596)
        STAT_SET_INT("H4LOOT_WEED_C", 0)
        STAT_SET_INT("H4LOOT_WEED_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_PAINT", 127)
        STAT_SET_INT("H4LOOT_PAINT_SCOPED", 127)
        STAT_SET_INT("H4LOOT_CASH_V", 598268)
        STAT_SET_INT("H4LOOT_COKE_V", 1196536)
        STAT_SET_INT("H4LOOT_GOLD_V", 1595382)
        STAT_SET_INT("H4LOOT_PAINT_V", 1196536)
        STAT_SET_INT("H4LOOT_WEED_V", 957229)
        STAT_SET_INT("H4_PROGRESS", 126823)
        STAT_SET_INT("H4CNF_BS_GEN", 262143)
        STAT_SET_INT("H4CNF_BS_ENTR", 63)
        STAT_SET_INT("H4CNF_BS_ABIL", 63)
        STAT_SET_INT("H4CNF_WEP_DISRP", 3)
        STAT_SET_INT("H4CNF_ARM_DISRP", 3)
        STAT_SET_INT("H4CNF_HEL_DISRP", 3)
        STAT_SET_INT("H4CNF_APPROACH", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_BOLTCUT", 4424)
        STAT_SET_INT("H4CNF_UNIFORM", 5256)
        STAT_SET_INT("H4CNF_GRAPPEL", 5156)
        STAT_SET_INT("H4_MISSIONS", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_WEAPONS", 1)
        STAT_SET_INT("H4CNF_TROJAN", 5)
        STAT_SET_INT("H4_PLAYTHROUGH_STATUS", 100)
        -- INT
        SET_FLOAT_GLOBAL(262145+29470,-0.1)
        SET_FLOAT_GLOBAL(262145+29471,-0.02)
        SET_INT_GLOBAL(262145+29227,1800)
        SET_INT_GLOBAL(1711169,30)
        SET_INT_GLOBAL(1711170,35)
        SET_INT_GLOBAL(1711171,35)
    end,
    ["P_QUADRO"] = function()
        STAT_SET_INT("H4CNF_TARGET", 5)
        STAT_SET_INT("H4LOOT_CASH_I", 2359448)
        STAT_SET_INT("H4LOOT_CASH_I_SCOPED", 2359448)
        STAT_SET_INT("H4LOOT_CASH_C", 0)
        STAT_SET_INT("H4LOOT_CASH_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_COKE_I", 4901222)
        STAT_SET_INT("H4LOOT_COKE_I_SCOPED", 4901222)
        STAT_SET_INT("H4LOOT_COKE_C", 0)
        STAT_SET_INT("H4LOOT_COKE_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_I", 0)
        STAT_SET_INT("H4LOOT_GOLD_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_C", 255)
        STAT_SET_INT("H4LOOT_GOLD_C_SCOPED", 255)
        STAT_SET_INT("H4LOOT_WEED_I", 0)
        STAT_SET_INT("H4LOOT_WEED_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_WEED_C", 0)
        STAT_SET_INT("H4LOOT_WEED_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_PAINT", 127)
        STAT_SET_INT("H4LOOT_PAINT_SCOPED", 127)
        STAT_SET_INT("H4LOOT_CASH_V", 599431)
        STAT_SET_INT("H4LOOT_COKE_V", 1198863)
        STAT_SET_INT("H4LOOT_GOLD_V", 1598484)
        STAT_SET_INT("H4LOOT_PAINT_V", 1198863)
        STAT_SET_INT("H4LOOT_WEED_V", 0)
        STAT_SET_INT("H4_PROGRESS", 126823)
        STAT_SET_INT("H4CNF_BS_GEN", 262143)
        STAT_SET_INT("H4CNF_BS_ENTR", 63)
        STAT_SET_INT("H4CNF_BS_ABIL", 63)
        STAT_SET_INT("H4CNF_WEP_DISRP", 3)
        STAT_SET_INT("H4CNF_ARM_DISRP", 3)
        STAT_SET_INT("H4CNF_HEL_DISRP", 3)
        STAT_SET_INT("H4CNF_APPROACH", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_BOLTCUT", 4424)
        STAT_SET_INT("H4CNF_UNIFORM", 5256)
        STAT_SET_INT("H4CNF_GRAPPEL", 5156)
        STAT_SET_INT("H4_MISSIONS", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_WEAPONS", 1)
        STAT_SET_INT("H4CNF_TROJAN", 5)
        STAT_SET_INT("H4_PLAYTHROUGH_STATUS", 100)
        -- INT
        SET_FLOAT_GLOBAL(262145+29470,-0.1)
        SET_FLOAT_GLOBAL(262145+29471,-0.02)
        SET_INT_GLOBAL(262145+29227,1800)
        SET_INT_GLOBAL(1711169,25)
        SET_INT_GLOBAL(1711170,25)
        SET_INT_GLOBAL(1711171,25)
        SET_INT_GLOBAL(1711172,25)
    end,
    ["P_QUADRO2"] = function()
        STAT_SET_INT("H4CNF_TARGET", 1)
        STAT_SET_INT("H4LOOT_CASH_I", 9208137)
        STAT_SET_INT("H4LOOT_CASH_I_SCOPED", 9208137)
        STAT_SET_INT("H4LOOT_CASH_C", 0)
        STAT_SET_INT("H4LOOT_CASH_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_COKE_I", 1048704)
        STAT_SET_INT("H4LOOT_COKE_I_SCOPED", 1048704)
        STAT_SET_INT("H4LOOT_COKE_C", 0)
        STAT_SET_INT("H4LOOT_COKE_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_I", 0)
        STAT_SET_INT("H4LOOT_GOLD_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_C", 255)
        STAT_SET_INT("H4LOOT_GOLD_C_SCOPED", 255)
        STAT_SET_INT("H4LOOT_WEED_I", 4206596)
        STAT_SET_INT("H4LOOT_WEED_I_SCOPED", 4206596)
        STAT_SET_INT("H4LOOT_WEED_C", 0)
        STAT_SET_INT("H4LOOT_WEED_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_PAINT", 127)
        STAT_SET_INT("H4LOOT_PAINT_SCOPED", 127)
        STAT_SET_INT("H4LOOT_CASH_V", 655681)
        STAT_SET_INT("H4LOOT_COKE_V", 1311363)
        STAT_SET_INT("H4LOOT_GOLD_V", 1748484)
        STAT_SET_INT("H4LOOT_PAINT_V", 1311363)
        STAT_SET_INT("H4LOOT_WEED_V", 1049090)
        STAT_SET_INT("H4_PROGRESS", 126823)
        STAT_SET_INT("H4CNF_BS_GEN", 262143)
        STAT_SET_INT("H4CNF_BS_ENTR", 63)
        STAT_SET_INT("H4CNF_BS_ABIL", 63)
        STAT_SET_INT("H4CNF_WEP_DISRP", 3)
        STAT_SET_INT("H4CNF_ARM_DISRP", 3)
        STAT_SET_INT("H4CNF_HEL_DISRP", 3)
        STAT_SET_INT("H4CNF_APPROACH", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_BOLTCUT", 4424)
        STAT_SET_INT("H4CNF_UNIFORM", 5256)
        STAT_SET_INT("H4CNF_GRAPPEL", 5156)
        STAT_SET_INT("H4_MISSIONS", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_WEAPONS", 1)
        STAT_SET_INT("H4CNF_TROJAN", 5)
        STAT_SET_INT("H4_PLAYTHROUGH_STATUS", 100)
        -- INT
        SET_FLOAT_GLOBAL(262145+29470,-0.1)
        SET_FLOAT_GLOBAL(262145+29471,-0.02)
        SET_INT_GLOBAL(262145+29227,1800)
        SET_INT_GLOBAL(1711169,25)
        SET_INT_GLOBAL(1711170,25)
        SET_INT_GLOBAL(1711171,25)
        SET_INT_GLOBAL(1711172,25)
    end,
    ["P_FULL"] = function()
        STAT_SET_INT("H4CNF_BS_GEN", 262143)
        STAT_SET_INT("H4CNF_BS_ENTR", 63)
        STAT_SET_INT("H4CNF_BS_ABIL", 63)
        STAT_SET_INT("H4CNF_WEP_DISRP", 3)
        STAT_SET_INT("H4CNF_ARM_DISRP", 3)
        STAT_SET_INT("H4CNF_HEL_DISRP", 3)
        STAT_SET_INT("H4CNF_BOLTCUT", 4424)
        STAT_SET_INT("H4CNF_UNIFORM", 5256)
        STAT_SET_INT("H4CNF_GRAPPEL", 5156)
        STAT_SET_INT("H4CNF_APPROACH", 0xFFFFFFF)
        STAT_SET_INT("H4LOOT_CASH_I", 1089792)
        STAT_SET_INT("H4LOOT_CASH_C", 0)
        STAT_SET_INT("H4LOOT_WEED_I", 9114214)
        STAT_SET_INT("H4LOOT_WEED_C", 37)
        STAT_SET_INT("H4LOOT_COKE_I", 6573209)
        STAT_SET_INT("H4LOOT_COKE_C", 26)
        STAT_SET_INT("H4LOOT_GOLD_I", 0)
        STAT_SET_INT("H4LOOT_GOLD_C", 192)
        STAT_SET_INT("H4LOOT_PAINT", 127)
        STAT_SET_INT("H4_PROGRESS", 124271)
        STAT_SET_INT("H4LOOT_CASH_V", 22500)
        STAT_SET_INT("H4LOOT_COKE_V", 55023)
        STAT_SET_INT("H4LOOT_GOLD_V", 83046)
        STAT_SET_INT("H4LOOT_PAINT_V", 47375)
        STAT_SET_INT("H4LOOT_WEED_V", 36967)
        STAT_SET_INT("H4LOOT_CASH_I_SCOPED", 1089792)
        STAT_SET_INT("H4LOOT_CASH_C_SCOPED", 0)
        STAT_SET_INT("H4LOOT_WEED_I_SCOPED", 9114214)
        STAT_SET_INT("H4LOOT_WEED_C_SCOPED", 37)
        STAT_SET_INT("H4LOOT_COKE_I_SCOPED", 6573209)
        STAT_SET_INT("H4LOOT_COKE_C_SCOPED", 26)
        STAT_SET_INT("H4LOOT_GOLD_I_SCOPED", 0)
        STAT_SET_INT("H4LOOT_GOLD_C_SCOPED", 192)
        STAT_SET_INT("H4LOOT_PAINT_SCOPED", 127)
        STAT_SET_INT("H4_MISSIONS", 0xFFFFFFF)
        STAT_SET_INT("H4_PLAYTHROUGH_STATUS", 5)
        -- INT
        STAT_SET_INT("H4CNF_TARGET", math.random(1, 5))
        STAT_SET_INT("H4CNF_WEAPONS", math.random(1, 5))
    end,
    -- CASINO
    ["C_SILENT_HARD"] = function()
        STAT_SET_INT("H3_COMPLETEDPOSIX", 0xFFFFFFF)
        STAT_SET_INT("CAS_HEIST_FLOW", 0xFFFFFFF)
        STAT_SET_INT("H3_LAST_APPROACH", 4)
        STAT_SET_INT("H3OPT_APPROACH", 1)
        STAT_SET_INT("H3_HARD_APPROACH", 1)
        STAT_SET_INT("H3OPT_TARGET", 3)
        STAT_SET_INT("H3OPT_POI", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_ACCESSPOINTS", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_BITSET1", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_CREWWEAP", 2)
        STAT_SET_INT("H3OPT_CREWDRIVER", 5)
        STAT_SET_INT("H3OPT_CREWHACKER", 4)
        STAT_SET_INT("H3OPT_WEAPS", 0)
        STAT_SET_INT("H3OPT_VEHS", 3)
        STAT_SET_INT("H3OPT_DISRUPTSHIP", 3)
        STAT_SET_INT("H3OPT_BODYARMORLVL", 3)
        STAT_SET_INT("H3OPT_KEYLEVELS", 2)
        STAT_SET_INT("H3OPT_MASKS", 2)
        STAT_SET_INT("H3OPT_BITSET0", 0xFFFFFFF)
    end,
    ["C_BIGCON"] = function()
        STAT_SET_INT("H3_COMPLETEDPOSIX", 0xFFFFFFF)
        STAT_SET_INT("CAS_HEIST_FLOW", 0xFFFFFFF)
        STAT_SET_INT("H3_LAST_APPROACH", 4)
        STAT_SET_INT("H3OPT_APPROACH", 1)
        STAT_SET_INT("H3_HARD_APPROACH", 0)
        STAT_SET_INT("H3OPT_TARGET", 3)
        STAT_SET_INT("H3OPT_POI", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_ACCESSPOINTS", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_BITSET1", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_CREWWEAP", 2)
        STAT_SET_INT("H3OPT_CREWDRIVER", 5)
        STAT_SET_INT("H3OPT_CREWHACKER", 4)
        STAT_SET_INT("H3OPT_WEAPS", 0)
        STAT_SET_INT("H3OPT_VEHS", 3)
        STAT_SET_INT("H3OPT_DISRUPTSHIP", 3)
        STAT_SET_INT("H3OPT_BODYARMORLVL", 3)
        STAT_SET_INT("H3OPT_KEYLEVELS", 2)
        STAT_SET_INT("H3OPT_MASKS", 2)
        STAT_SET_INT("H3OPT_BITSET0", 0xFFFFFFF)
    end,
    ["C_BIGCON_HARD"] = function()
        STAT_SET_INT("H3_COMPLETEDPOSIX", 0xFFFFFFF)
        STAT_SET_INT("CAS_HEIST_FLOW", 0xFFFFFFF)
        STAT_SET_INT("H3_LAST_APPROACH", 4)
        STAT_SET_INT("H3OPT_APPROACH", 2)
        STAT_SET_INT("H3_HARD_APPROACH", 2)
        STAT_SET_INT("H3OPT_TARGET", 3)
        STAT_SET_INT("H3OPT_POI", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_ACCESSPOINTS", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_BITSET1", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_CREWWEAP", 2)
        STAT_SET_INT("H3OPT_CREWDRIVER", 5)
        STAT_SET_INT("H3OPT_CREWHACKER", 4)
        STAT_SET_INT("H3OPT_WEAPS", 0)
        STAT_SET_INT("H3OPT_VEHS", 3)
        STAT_SET_INT("H3OPT_DISRUPTSHIP", 3)
        STAT_SET_INT("H3OPT_BODYARMORLVL", 3)
        STAT_SET_INT("H3OPT_KEYLEVELS", 2)
        STAT_SET_INT("H3OPT_MASKS", 2)
        STAT_SET_INT("H3OPT_BITSET0", 0xFFFFFFF)
    end,
    ["C_AGRESSIVE"] = function()
        STAT_SET_INT("H3_COMPLETEDPOSIX", 0xFFFFFFF)
        STAT_SET_INT("CAS_HEIST_FLOW", 0xFFFFFFF)
        STAT_SET_INT("H3_LAST_APPROACH", 4)
        STAT_SET_INT("H3OPT_APPROACH", 3)
        STAT_SET_INT("H3_HARD_APPROACH", 3)
        STAT_SET_INT("H3OPT_TARGET", 3)
        STAT_SET_INT("H3OPT_POI", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_ACCESSPOINTS", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_BITSET1", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_CREWWEAP", 2)
        STAT_SET_INT("H3OPT_CREWDRIVER", 5)
        STAT_SET_INT("H3OPT_CREWHACKER", 4)
        STAT_SET_INT("H3OPT_WEAPS", 1)
        STAT_SET_INT("H3OPT_VEHS", 3)
        STAT_SET_INT("H3OPT_DISRUPTSHIP", 3)
        STAT_SET_INT("H3OPT_BODYARMORLVL", 3)
        STAT_SET_INT("H3OPT_KEYLEVELS", 2)
        STAT_SET_INT("H3OPT_MASKS", 2)
        STAT_SET_INT("H3OPT_BITSET0", 0xFFFFFFF)
    end,
    ["C_AGRESSIVE_HARD"] = function()
        STAT_SET_INT("H3_COMPLETEDPOSIX", 0xFFFFFFF)
        STAT_SET_INT("CAS_HEIST_FLOW", 0xFFFFFFF)
        STAT_SET_INT("H3_LAST_APPROACH", 4)
        STAT_SET_INT("H3OPT_APPROACH", 3)
        STAT_SET_INT("H3_HARD_APPROACH", 0)
        STAT_SET_INT("H3OPT_TARGET", 3)
        STAT_SET_INT("H3OPT_POI", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_ACCESSPOINTS", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_BITSET1", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_CREWWEAP", 2)
        STAT_SET_INT("H3OPT_CREWDRIVER", 5)
        STAT_SET_INT("H3OPT_CREWHACKER", 4)
        STAT_SET_INT("H3OPT_WEAPS", 1)
        STAT_SET_INT("H3OPT_VEHS", 3)
        STAT_SET_INT("H3OPT_DISRUPTSHIP", 3)
        STAT_SET_INT("H3OPT_BODYARMORLVL", 3)
        STAT_SET_INT("H3OPT_KEYLEVELS", 2)
        STAT_SET_INT("H3OPT_MASKS", 2)
        STAT_SET_INT("H3OPT_BITSET0", 0xFFFFFFF)
    end,
    -- HEISTS
    ["H_COMPLETEPLANNING"] = function()
        STAT_SET_INT("HEIST_PLANNING_STAGE", 0xFFFFFFF)
    end,
    -- DOOMSDAY
    ["D_ACT1"] = function()
        STAT_SET_INT("GANGOPS_FLOW_MISSION_PROG", 503)
        STAT_SET_INT("GANGOPS_HEIST_STATUS", -229383)
        STAT_SET_INT("GANGOPS_FLOW_NotifyS", 1557)
    end,
    ["D_ACT2"] = function()
        STAT_SET_INT("GANGOPS_FLOW_MISSION_PROG", 240)
        STAT_SET_INT("GANGOPS_HEIST_STATUS", -229378)
        STAT_SET_INT("GANGOPS_FLOW_NotifyS", 1557)
    end,
    ["D_ACT3"] = function()
        STAT_SET_INT("GANGOPS_FLOW_MISSION_PROG", 16368)
        STAT_SET_INT("GANGOPS_HEIST_STATUS", -229380)
        STAT_SET_INT("GANGOPS_FLOW_NotifyS", 1557)
    end,
    -- TUNNER
    ["T_COMPLETE"] = function()
        STAT_SET_INT("TUNER_GEN_BS", 0xFFFFFFF)
    end,
    ["T_UNION"] = function()
        STAT_SET_INT("TUNER_GEN_BS", 12543)
        STAT_SET_INT("TUNER_CURRENT", 0)
    end,
    ["T_SUPERDOLLAR"] = function()
        STAT_SET_INT("TUNER_GEN_BS", 4351)
        STAT_SET_INT("TUNER_CURRENT", 1)
    end,
    ["T_BANK"] = function()
        STAT_SET_INT("TUNER_GEN_BS", 12543)
        STAT_SET_INT("TUNER_CURRENT", 2)
    end,
    ["T_ECU"] = function()
        STAT_SET_INT("TUNER_GEN_BS", 12543)
        STAT_SET_INT("TUNER_CURRENT", 3)
    end,
    ["T_PRISON"] = function()
        STAT_SET_INT("TUNER_GEN_BS", 12543)
        STAT_SET_INT("TUNER_CURRENT", 4)
    end,
    ["T_AGENCY"] = function()
        STAT_SET_INT("TUNER_GEN_BS", 12543)
        STAT_SET_INT("TUNER_CURRENT", 5)
    end,
    ["T_LOST"] = function()
        STAT_SET_INT("TUNER_GEN_BS", 12543)
        STAT_SET_INT("TUNER_CURRENT", 6)
    end,
    ["T_DATA"] = function()
        STAT_SET_INT("TUNER_GEN_BS", 12543)
        STAT_SET_INT("TUNER_CURRENT", 7)
    end,
}

local CUTS_TBL = {
    ["PERICO"] = {
        1711169,
        1711170,
        1711171,
        1711174
    },
    ["CASINO"] = {
        1703513 + 2325 + 1,
        1703513 + 2325 + 2,
        1703513 + 2325 + 3,
        1703513 + 2325 + 4,
    },
    ["CASINO"] = {
        1699568 + 812 + 50 + 1,
        1699568 + 812 + 50 + 2,
        1699568 + 812 + 50 + 3,
        1699568 + 812 + 50 + 4,
    },
    ["HEIST"] = {
        1671773 + 3008 + 1,
        1671773 + 3008 + 2,
        1671773 + 3008 + 3,
        1671773 + 3008 + 4,
    },
    ["TUNNERS"] = {
        262145 + 30514 + 0,
        262145 + 30514 + 1,
        262145 + 30514 + 2,
        262145 + 30514 + 3,
        262145 + 30514 + 4,
        262145 + 30514 + 5,
        262145 + 30514 + 6,
        262145 + 30514 + 7,
        262145 + 30514 + 8,
        262145 + 30514 + 9,
    }
}

local CUTS = {
    ["PERICO"] = function(target, percentage)
        local global_id = CUTS_TBL["PERICO"][target]
        if not global_id then
            return "Invalid receiver (" .. target .. ")"
        end
        SET_INT_GLOBAL(global_id, percentage or 150)
    end,
    ["CASINO"] = function(target, percentage)
        local global_id = CUTS_TBL["CASINO"][target]
        if not global_id then
            return "Invalid receiver (" .. target .. ")"
        end
        SET_INT_GLOBAL(global_id, percentage or 150)
    end,
    ["HEIST"] = function(target, percentage)
        local global_id = CUTS_TBL["HEIST"][target]
        if not global_id then
            return "Invalid receiver (" .. target .. ")"
        end
        SET_INT_GLOBAL(global_id, percentage or 150)
    end,
    ["TUNNERS"] = function(target, percentage)
        local global_id = CUTS_TBL["TUNNERS"][target]
        if not global_id then
            return "Invalid receiver (" .. target .. ")"
        end
        SET_INT_GLOBAL(global_id, percentage or 150)
        SET_INT_GLOBAL(262145 + 30511, 0)
    end,
}

local FEATURES = {
    ["P_BAG"] = function(data)
        local num = tonumber(data) or 1
        num = math.min(4, num)
        local bag_balue = 1800 * num
        SET_INT_GLOBAL(262145, bag_balue)
    end,
    ["P_FEE"] = function()
        SET_FLOAT_GLOBAL(262145+29470,0)
        SET_FLOAT_GLOBAL(262145+29471,0)
    end,
    ["P_VEHICLE"] = function()
        STAT_SET_INT("H4_MISSIONS", 0xFFFFFFF)
    end,
    ["P_LOOT"] = function()
        STAT_SET_INT("H4LOOT_CASH_I", 1319624)
        STAT_SET_INT("H4LOOT_CASH_C", 18)
        STAT_SET_INT("H4LOOT_CASH_V", 89400)
        STAT_SET_INT("H4LOOT_WEED_I", 2639108)
        STAT_SET_INT("H4LOOT_WEED_C", 36)
        STAT_SET_INT("H4LOOT_WEED_V", 149000)
        STAT_SET_INT("H4LOOT_COKE_I", 4229122)
        STAT_SET_INT("H4LOOT_COKE_C", 72)
        STAT_SET_INT("H4LOOT_COKE_V", 221200)
        STAT_SET_INT("H4LOOT_GOLD_I", 8589313)
        STAT_SET_INT("H4LOOT_GOLD_C", 129)
        STAT_SET_INT("H4LOOT_GOLD_V", 322600)
        STAT_SET_INT("H4LOOT_PAINT", 127)
        STAT_SET_INT("H4LOOT_PAINT_V", 186800)
        STAT_SET_INT("H4LOOT_CASH_I_SCOPED", 1319624)
        STAT_SET_INT("H4LOOT_CASH_C_SCOPED", 18)
        STAT_SET_INT("H4LOOT_WEED_I_SCOPED", 2639108)
        STAT_SET_INT("H4LOOT_WEED_C_SCOPED", 36)
        STAT_SET_INT("H4LOOT_COKE_I_SCOPED", 4229122)
        STAT_SET_INT("H4LOOT_COKE_C_SCOPED", 72)
        STAT_SET_INT("H4LOOT_GOLD_I_SCOPED", 8589313)
        STAT_SET_INT("H4LOOT_GOLD_C_SCOPED", 129)
        STAT_SET_INT("H4LOOT_PAINT_SCOPED", 127)
    end,
    ["P_COMPOUND"] = function()
        STAT_SET_INT("H4LOOT_CASH_C", 2)
        STAT_SET_INT("H4LOOT_CASH_V", 474431)
        STAT_SET_INT("H4LOOT_WEED_C", 17)
        STAT_SET_INT("H4LOOT_WEED_V", 759090)
        STAT_SET_INT("H4LOOT_COKE_C", 132)
        STAT_SET_INT("H4LOOT_COKE_V", 948863)
        STAT_SET_INT("H4LOOT_GOLD_C", 104)
        STAT_SET_INT("H4LOOT_GOLD_V", 1265151)
        STAT_SET_INT("H4LOOT_PAINT", 127)
        STAT_SET_INT("H4LOOT_PAINT_V", 948863)
        STAT_SET_INT("H4LOOT_CASH_C_SCOPED", 2)
        STAT_SET_INT("H4LOOT_WEED_C_SCOPED", 17)
        STAT_SET_INT("H4LOOT_COKE_C_SCOPED", 132)
        STAT_SET_INT("H4LOOT_GOLD_C_SCOPED", 104)
        STAT_SET_INT("H4LOOT_PAINT_SCOPED", 127)
    end,
    ["P_WEAPON"] = function(data)
        local num = tonumber(data) or 1
        num = math.max(math.min(5, num), 1)
        STAT_SET_INT("H4CNF_WEAPONS", num)
    end,
    ["P_EQUIPMENT"] = function(data)
        local num = tonumber(data) or 1
        if num == 1 then
            STAT_SET_INT("H4CNF_GRAPPEL", 2022)
            STAT_SET_INT("H4CNF_UNIFORM", 12)
            STAT_SET_INT("H4CNF_BOLTCUT", 4161)
            STAT_SET_INT("H4CNF_TROJAN", 1)
        elseif num == 2 then
            STAT_SET_INT("H4CNF_GRAPPEL", 3671)
            STAT_SET_INT("H4CNF_UNIFORM", 5256)
            STAT_SET_INT("H4CNF_BOLTCUT", 4424)
            STAT_SET_INT("H4CNF_TROJAN", 2)
        elseif num == 3 then
            STAT_SET_INT("H4CNF_GRAPPEL", 85324)
            STAT_SET_INT("H4CNF_UNIFORM", 61034)
            STAT_SET_INT("H4CNF_BOLTCUT", 4612)
            STAT_SET_INT("H4CNF_TROJAN", 5)
        end
    end,
    ["P_TRUCK"] = function(data)
        local num = tonumber(data) or 1
        num = math.max(math.min(5, num), 1)
        STAT_SET_INT("H4CNF_TROJAN", num)
    end,
    ["P_DIFFICULTY"] = function(data)
        local num = tonumber(data) or 1
        local need = num == 1 and 126823 or 131055
        STAT_SET_INT("H4_PROGRESS", num)
    end,
    ["P_AWARD"] = function()
        STAT_SET_BOOL("AWD_INTELGATHER", true)
        STAT_SET_BOOL("AWD_COMPOUNDINFILT", true)
        STAT_SET_BOOL("AWD_LOOT_FINDER", true)
        STAT_SET_BOOL("AWD_MAX_DISRUPT", true)
        STAT_SET_BOOL("AWD_THE_ISLAND_HEIST", true)
        STAT_SET_BOOL("AWD_GOING_ALONE", true)
        STAT_SET_BOOL("AWD_TEAM_WORK", true)
        STAT_SET_BOOL("AWD_MIXING_UP", true)
        STAT_SET_BOOL("AWD_PRO_THIEF", true)
        STAT_SET_BOOL("AWD_CAT_BURGLAR", true)
        STAT_SET_BOOL("AWD_ONE_OF_THEM", true)
        STAT_SET_BOOL("AWD_GOLDEN_GUN", true)
        STAT_SET_BOOL("AWD_ELITE_THIEF", true)
        STAT_SET_BOOL("AWD_PROFESSIONAL", true)
        STAT_SET_BOOL("AWD_HELPING_OUT", true)
        STAT_SET_BOOL("AWD_COURIER", true)
        STAT_SET_BOOL("AWD_PARTY_VIBES", true)
        STAT_SET_BOOL("AWD_HELPING_HAND", true)
        STAT_SET_BOOL("AWD_ELEVENELEVEN", true)
        STAT_SET_BOOL("COMPLETE_H4_F_USING_VETIR", true)
        STAT_SET_BOOL("COMPLETE_H4_F_USING_LONGFIN", true)
        STAT_SET_BOOL("COMPLETE_H4_F_USING_ANNIH", true)
        STAT_SET_BOOL("COMPLETE_H4_F_USING_ALKONOS", true)
        STAT_SET_BOOL("COMPLETE_H4_F_USING_PATROLB", true)
        -- BOOL
        STAT_SET_INT("AWD_LOSTANDFOUND", 500000)
        STAT_SET_INT("AWD_SUNSET", 1800000)
        STAT_SET_INT("AWD_TREASURE_HUNTER", 1000000)
        STAT_SET_INT("AWD_WRECK_DIVING", 1000000)
        STAT_SET_INT("AWD_KEINEMUSIK", 1800000)
        STAT_SET_INT("AWD_PALMS_TRAX", 1800000)
        STAT_SET_INT("AWD_MOODYMANN", 1800000)
        STAT_SET_INT("AWD_FILL_YOUR_BAGS", 1000000000)
        STAT_SET_INT("AWD_WELL_PREPARED", 80)
        STAT_SET_INT("H4_H4_DJ_MISSIONS", 0xFFFFFFF)
    end,
    ["P_COMPLETE"] = function()
        STAT_SET_INT("H4_MISSIONS", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_APPROACH", 0xFFFFFFF)
        STAT_SET_INT("H4CNF_BS_ENTR", 63)
        STAT_SET_INT("H4CNF_BS_GEN", 63)
        STAT_SET_INT("H4CNF_WEP_DISRP", 3)
        STAT_SET_INT("H4CNF_ARM_DISRP", 3)
        STAT_SET_INT("H4CNF_HEL_DISRP", 3)
    end,
    ["P_CUTSCENE"] = function()
        STAT_SET_INT("H4_PLAYTHROUGH_STATUS", 0)
    end,
    ["P_RESET"] = function()
        STAT_SET_INT("H4_MISSIONS", 0)
        STAT_SET_INT("H4_PROGRESS", 0)
        STAT_SET_INT("H4CNF_APPROACH", 0)
        STAT_SET_INT("H4CNF_BS_ENTR", 0)
        STAT_SET_INT("H4CNF_BS_GEN", 0)
        STAT_SET_INT("H4_PLAYTHROUGH_STATUS", 0)
    end,
    -- CASINO
    ["C_BOARD"] = function()
        STAT_SET_INT("H3OPT_POI", 0xFFFFFFF)
        STAT_SET_INT("H3OPT_ACCESSPOINTS", 2047)
    end,
    ["C_TARGET"] = function(data)
        local num = tonumber(data) or 0
        num = math.max(math.min(3, num), 0)
        STAT_SET_INT("H3OPT_TARGET", num)
    end,
    ["C_MODPAYOUT"] = function(data)
        STAT_SET_INT("H3OPT_TARGET", 3)
        STAT_SET_INT("H3_LAST_APPROACH", 0)
        STAT_SET_INT("H3_HARD_APPROACH", 0)
        -- INT
        SET_INT_GLOBAL(1703513+2326,42)
        SET_INT_GLOBAL(1703513+2326+1,100)
        SET_INT_GLOBAL(1703513+2326+2,100)
        SET_INT_GLOBAL(1703513+2326+3,100)
        SET_INT_GLOBAL(262145+28306,1410065408)
    end,
    ["C_MODPOTENCIAL"] = function(data)
        SET_INT_GLOBAL(262145 + 28303, 1410065408)
        SET_INT_GLOBAL(262145 + 28304, 1410065408)
        SET_INT_GLOBAL(262145 + 28305, 1410065408)
        SET_INT_GLOBAL(262145 + 28306, 1410065408)
    end,
    ["C_ADVCREW"] = function(data)
        STAT_SET_INT("H3OPT_CREWWEAP", 6)
        STAT_SET_INT("H3OPT_CREWDRIVER", 6)
        STAT_SET_INT("H3OPT_CREWHACKER", 6)
    end,
    ["C_AWARD"] = function()
        STAT_SET_INT("CAS_HEIST_NOTS", 0xFFFFFFF)
        STAT_SET_INT("CH_ARC_CAB_CLAW_TROPHY", 0xFFFFFFF)
        STAT_SET_INT("CH_ARC_CAB_LOVE_TROPHY", 0xFFFFFFF)
        STAT_SET_INT("SIGNAL_JAMMERS_COLLECTED", 50)
        STAT_SET_INT("AWD_ODD_JOBS", 52)
        STAT_SET_INT("AWD_PREPARATION", 40)
        STAT_SET_INT("AWD_ASLEEPONJOB", 20)
        STAT_SET_INT("AWD_DAICASHCRAB", 100000)
        STAT_SET_INT("AWD_BIGBRO", 40)
        STAT_SET_INT("AWD_SHARPSHOOTER", 40)
        STAT_SET_INT("AWD_RACECHAMP", 40)
        STAT_SET_INT("AWD_BATSWORD", 1000000)
        STAT_SET_INT("AWD_COINPURSE", 950000)
        STAT_SET_INT("AWD_ASTROCHIMP", 3000000)
        STAT_SET_INT("AWD_MASTERFUL", 40000)
        STAT_SET_INT("H3_BOARD_DIALOGUE0", 0xFFFFFFF)
        STAT_SET_INT("H3_BOARD_DIALOGUE1", 0xFFFFFFF)
        STAT_SET_INT("H3_BOARD_DIALOGUE2", 0xFFFFFFF)
        STAT_SET_INT("H3_VEHICLESUSED", 0xFFFFFFF)
        -- INT
        STAT_SET_BOOL("AWD_FIRST_TIME1", true)
        STAT_SET_BOOL("AWD_FIRST_TIME2", true)
        STAT_SET_BOOL("AWD_FIRST_TIME3", true)
        STAT_SET_BOOL("AWD_FIRST_TIME4", true)
        STAT_SET_BOOL("AWD_FIRST_TIME5", true)
        STAT_SET_BOOL("AWD_FIRST_TIME6", true)
        STAT_SET_BOOL("AWD_ALL_IN_ORDER", true)
        STAT_SET_BOOL("AWD_SUPPORTING_ROLE", true)
        STAT_SET_BOOL("AWD_LEADER", true)
        STAT_SET_BOOL("AWD_ODD_JOBS", true)
        STAT_SET_BOOL("AWD_SURVIVALIST", true)
        STAT_SET_BOOL("AWD_SCOPEOUT", true)
        STAT_SET_BOOL("AWD_CREWEDUP", true)
        STAT_SET_BOOL("AWD_MOVINGON", true)
        STAT_SET_BOOL("AWD_PROMOCAMP", true)
        STAT_SET_BOOL("AWD_GUNMAN", true)
        STAT_SET_BOOL("AWD_SMASHNGRAB", true)
        STAT_SET_BOOL("AWD_INPLAINSI", true)
        STAT_SET_BOOL("AWD_UNDETECTED", true)
        STAT_SET_BOOL("AWD_ALLROUND", true)
        STAT_SET_BOOL("AWD_ELITETHEIF", true)
        STAT_SET_BOOL("AWD_PRO", true)
        STAT_SET_BOOL("AWD_SUPPORTACT", true)
        STAT_SET_BOOL("AWD_SHAFTED", true)
        STAT_SET_BOOL("AWD_COLLECTOR", true)
        STAT_SET_BOOL("AWD_DEADEYE", true)
        STAT_SET_BOOL("AWD_PISTOLSATDAWN", true)
        STAT_SET_BOOL("AWD_TRAFFICAVOI", true)
        STAT_SET_BOOL("AWD_CANTCATCHBRA", true)
        STAT_SET_BOOL("AWD_WIZHARD", true)
        STAT_SET_BOOL("AWD_APEESCAPE", true)
        STAT_SET_BOOL("AWD_MONKEYKIND", true)
        STAT_SET_BOOL("AWD_AQUAAPE", true)
        STAT_SET_BOOL("AWD_KEEPFAITH", true)
        STAT_SET_BOOL("AWD_TRUELOVE", true)
        STAT_SET_BOOL("AWD_NEMESIS", true)
        STAT_SET_BOOL("AWD_FRIENDZONED", true)
        STAT_SET_BOOL("VCM_FLOW_CS_RSC_SEEN", true)
        STAT_SET_BOOL("VCM_FLOW_CS_BWL_SEEN", true)
        STAT_SET_BOOL("VCM_FLOW_CS_MTG_SEEN", true)
        STAT_SET_BOOL("VCM_FLOW_CS_OIL_SEEN", true)
        STAT_SET_BOOL("VCM_FLOW_CS_DEF_SEEN", true)
        STAT_SET_BOOL("VCM_FLOW_CS_FIN_SEEN", true)
        STAT_SET_BOOL("CAS_VEHICLE_REWARD", false)
        STAT_SET_BOOL("HELP_FURIA", true)
        STAT_SET_BOOL("HELP_MINITAN", true)
        STAT_SET_BOOL("HELP_YOSEMITE2", true)
        STAT_SET_BOOL("HELP_ZHABA", true)
        STAT_SET_BOOL("HELP_IMORGEN", true)
        STAT_SET_BOOL("HELP_SULTAN2", true)
        STAT_SET_BOOL("HELP_VAGRANT", true)
        STAT_SET_BOOL("HELP_VSTR", true)
        STAT_SET_BOOL("HELP_STRYDER", true)
        STAT_SET_BOOL("HELP_SUGOI", true)
        STAT_SET_BOOL("HELP_KANJO", true)
        STAT_SET_BOOL("HELP_FORMULA", true)
        STAT_SET_BOOL("HELP_FORMULA2", true)
        STAT_SET_BOOL("HELP_JB7002", true)
    end,
    ["C_REMOVECOOLDOWN"] = function()
        STAT_SET_INT("H3_COMPLETEDPOSIX", 0xFFFFFFF)
        STAT_SET_INT("MPPLY_H3_COOLDOWN", 0xFFFFFFF)
    end,
    ["C_SKIPAGATHA"] = function()
        STAT_SET_INT("VCM_FLOW_PROGRESS", 0xFFFFFFF)
        STAT_SET_INT("VCM_STORY_PROGRESS", 5)
        -- INT
        STAT_SET_BOOL("AWD_LEADER", true)
        STAT_SET_BOOL("VCM_FLOW_CS_FIN_SEEN", true)
    end,
    -- misc
    ["TUNNER_XP"] = function(data)
        local num = tonumber(data) or 997430
        STAT_SET_INT("CAR_CLUB_REP", num)
    end,
    ["T_RESETMISSION"] = function(data)
        STAT_SET_INT("TUNER_GEN_BS", 12467)
    end,
    ["T_RESETCONTRACT"] = function(data)
        STAT_SET_INT("TUNER_GEN_BS", 8371)
        STAT_SET_INT("TUNER_CURRENT", 0xFFFFFFF)
    end,
    ["T_RESETGAIN"] = function(data)
        STAT_SET_INT("TUNER_COUNT", 0)
        STAT_SET_INT("TUNER_EARNINGS", 0)
    end,
}

local function RunPreset(info)
    local need, data
    for name, func in pairs(PRESETS) do
        if info:sub(1, #name) == name then
            need = func
            data = info:sub(#name + 1)
            break
        end
    end
    system.fiber(function()
        local problem = need(data)
        if problem then
            console.log(con_color.Red, "HeistManager: " .. problem .. "\n")
        end
    end)
end

local function RunFeature(info)
    local need, data
    for name, func in pairs(FEATURES) do
        if info:sub(1, #name) == name then
            need = func
            data = info:sub(#name + 1)
            break
        end
    end
    system.fiber(function()
        local problem = need(data)
        if problem then
            console.log(con_color.Red, "HeistManager: " .. problem .. "\n")
        end
    end)
end

local function split(s, delimiter)
    local result = {}
    for match in (s..delimiter):gmatch("(.-)"..delimiter) do
        table.insert(result, match)
    end
    return result
end

local function RunCut(info)
    local need, data
    for name, func in pairs(CUTS) do
        if info:sub(1, #name) == name then
            need = func
            data = info:sub(#name + 2)
            break
        end
    end
    local args = split(data, " ")
    system.fiber(function()
        local problem = need(tonumber(args[1]), tonumber(args[2]))
        if problem then
            console.log(con_color.Red, "HeistManager: " .. problem .. "\n")
        end
    end)
end

local prefixes = {
    ["!hpreset "] = RunPreset,
    ["!hfeature "] = RunFeature,
    ["!hcut "] = RunCut,
    ["!htp "] = function(info)
        local pos = POSITIONS[info]
        if not pos then
            console.log(con_color.Red, "HeistManager: Teleport point not found\n")
            return
        end
        print("Teleporting")
        utils.teleport(pos)
    end,
}

function OnChatMsg(index, text)
	if index ~= player.index() then return end
    for prefix, func in pairs(prefixes) do
        local l = #prefix
        if text:sub(1, l) == prefix then
            local info = text:sub(l + 1)
            func(info)
            return
        end
    end
end
